<?php
    $infoCustomer = 'form_additional_info_customer_edit';
    $blockName = $this->getNameInLayout();
    
    if($infoCustomer == $blockName){
        $blockData = $block->getCustomer();
    } else {
        $blockData = $block->getFormData();
    }
?>
<?php $_legalType = $block->getLayout()->createBlock('Techspot\Brcustomer\Block\Widget\Legaltype') ?>
<?php if ($_legalType->isEnabled()): ?>
    <?= $_legalType->setTaxvat($blockData->getLegalType())->toHtml() ?>
<?php endif ?>

<?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
<?php if ($_taxvat->isEnabled()): ?>    
    <?= $_taxvat->setTaxvat($blockData->getTaxvat())->toHtml() ?>
<?php endif ?>

<?php $_document = $block->getLayout()->createBlock('Techspot\Brcustomer\Block\Widget\Document') ?>
<?php if ($_document->isEnabled()): ?>
    <?= $_document->setTaxvat($blockData->getDocument())->toHtml() ?>
<?php endif ?>

<?php $_documentEmitter = $block->getLayout()->createBlock('Techspot\Brcustomer\Block\Widget\Documentemitter') ?>
<?php if ($_documentEmitter->isEnabled()): ?>
    <?= $_documentEmitter->setTaxvat($blockData->getDocumentEmitter())->toHtml() ?>
<?php endif ?>

<?php $_stateInscription = $block->getLayout()->createBlock('Techspot\Brcustomer\Block\Widget\Stateinscription') ?>
<?php if ($_stateInscription->isEnabled()): ?>
    <?= $_stateInscription->setTaxvat($blockData->getStateInscription())->toHtml() ?>
<?php endif ?>

<?php $_countyInscription = $block->getLayout()->createBlock('Techspot\Brcustomer\Block\Widget\Countyinscription') ?>
<?php if ($_countyInscription->isEnabled()): ?>
    <?= $_countyInscription->setTaxvat($blockData->getCountyInscription())->toHtml() ?>
<?php endif ?>

<script type="text/javascript">
require([
    'jquery',
    'brcustomer',
    'pessoaFisica',
    "pessoaJuridica",
    'domReady!'
], function($){
});
</script>