<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Widget\Gender $block */
?>
<div class="field legal-type<?php if ($block->isRequired()) echo ' required' ?>">
    <label class="label" for="<?= $block->escapeHtmlAttr($block->getFieldId('legal_type')) ?>"><span><?= $block->escapeHtml(__('Legal Type')) ?></span></label>
    <div class="control">
        <select id="<?= $block->escapeHtmlAttr($block->getFieldId('legal_type')) ?>" name="<?= $block->escapeHtmlAttr($block->getFieldName('legal_type')) ?>" title="<?= $block->escapeHtmlAttr(__('Legal Type')) ?>"<?php if ($block->isRequired()):?> class="validate-select" data-validate="{required:true}"<?php endif; ?>>
            <?php $options = $block->getLegalTypeOptions(); ?>
            <?php $value = $block->getLegalType();?>
            <?php foreach ($options as $option):?>
                <option value="<?= $block->escapeHtmlAttr($option->getValue()) ?>"<?php if ($option->getValue() == $value) echo ' selected="selected"' ?>><?= $block->escapeHtml(__($option->getLabel())) ?></option>
            <?php endforeach;?>
        </select>
    </div>
</div>

